AWSTemplateFormatVersion: 2010-09-09
Description: Demo use of !Join
Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-017b0e29fac27906b
      InstanceType: t2.nano
      SubnetId: subnet-074ce7a864d83c7b2
      Tags:
        - Key: Name 
          Value: Simple instance
        - Key: Location
          Value: !Join [ " ", [ Server, in, AWS, London ] ]
        - Key: Nickname
          Value: AmazonLinuxInstance